# Changes here will be overwritten by Copier
_commit: v0.0.1
_src_path: /Users/sabard/dev/util/python_package_template
author_email: s@bardasgupta.com
author_first_name: Sabar
author_full_name: Sabar Dasgupta
author_last_name: Dasgupta
package_name: watch-calibration
pytest: false
python_requires: '>=3.8'
python_version: 3.10.14
